# Generated by Django 5.2.5 on 2025-08-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banners/', verbose_name='بنر')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۱')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۲')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۳')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۴')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۵')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۶')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۷')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۸')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۹')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۱۰')),
                ('image11', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۱۱')),
                ('image12', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۱۲')),
                ('image13', models.ImageField(blank=True, null=True, upload_to='mainpage/', verbose_name='عکس ۱۳')),
            ],
        ),
    ]
