# Generated by Django 5.2.5 on 2025-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۱'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۱۰'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۱۱'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۱۲'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image13',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۱۳'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۲'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۳'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۴'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۵'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۶'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۷'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۸'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس ۹'),
        ),
    ]
