# Generated by Django 5.2.5 on 2025-08-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_mainpage_image1_alter_mainpage_image10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
