# Generated by Django 5.2.5 on 2025-08-26 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_mainpage_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image9',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='link',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainpage.mainpage')),
            ],
        ),
    ]
