# Generated by Django 5.2.5 on 2025-08-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_remove_mainpage_image1_remove_mainpage_image10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='banner',
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='بنر')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='mainpage.mainpage')),
            ],
        ),
    ]
