# Generated by Django 5.2.5 on 2025-08-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_remove_mainpage_banner_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageImage',
            new_name='Image',
        ),
    ]
