# Generated by Django 5.2.5 on 2025-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_rename_pageimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link1',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
