# Generated by Django 5.2.5 on 2025-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_image_link1'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
