# Generated by Django 5.2.5 on 2025-09-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_image_title1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
