# Generated by Django 5.2.5 on 2025-09-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_alter_banner_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
